sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t jiangwensi/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jiangwensi/docker-react npm run test
